src/Webapp/Controllers/UsermanagementController.cs
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unity;
using System.Security.Policy;
using System.Threading.Tasks;
using Webapp.Dtos;
using Webapp.Models;
using System.Data.Entity;

namespace Webapp.Controllers
{
    [Authorize(Roles = "Manager")]
    public class UsermanagementController : Controller
    {
        //private ApplicationUserManager _userManager;
        private readonly ApplicationDbContext _context;

        public UsermanagementController()
        {
            
        }
        //public UsermanagementController(ApplicationUserManager userManager)
        //{
        //    UserManager = userManager;
        //}

        public UsermanagementController(ApplicationDbContext context)
        {
            _context = context;
        }

        //public ApplicationUserManager UserManager
        //{
        //    get
        //    {
        //        return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
        //    }
        //    private set
        //    {
        //        _userManager = value;
        //    }
        //}
        // GET: Usermanagement
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateUser()
        {
            return View();
        }

        public ActionResult LoadUsers()
        {
 
            var data = (from user in _context.Users
                                  select new
                                  {
                                      UserId = user.Id,
                                      user.Email,
                                      user.FirstName, user.LastName,user.IsEnabled,user.JobTitle,user.EmailConfirmed,
                                      RoleNames = (from userRole in user.Roles
                                                   join role in _context.Roles on userRole.RoleId
                                                   equals role.Id
                                                   select role.Name).ToList()
                                  }).ToList().Select(p => new UsersDto()
                                  {
                                      UserId = p.UserId,
                                      Email = p.Email,
                                      IsEnabled = p.IsEnabled,
                                      FullName = p.FirstName + " " + p.LastName,
                                      RoleName = string.Join(",", p.RoleNames),
                                      JobTitle = p.JobTitle,
                                      EmailConfirmed = p.EmailConfirmed
                                  });
            return Json(new { data }, JsonRequestBehavior.AllowGet);
        }


        public async Task<ActionResult> DisableUser(string Id)
        {
            if (Id == null)
            {
                return Json(new { success = false, message = "Invalid link" }, JsonRequestBehavior.AllowGet);
            }
            var user = await _context.Users.Where(x => x.Id == Id).SingleOrDefaultAsync();
            if (user == null)
            {
                return Json(new { success = false, message = "User not found" }, JsonRequestBehavior.AllowGet);
            }
            if(user.Id == User.Identity.GetUserId())
            {
                return Json(new { success = false, message = "You cannot disable you own account" }, JsonRequestBehavior.AllowGet);

            }
            user.IsEnabled = false;
            _context.Entry(user).State = EntityState.Modified;
            var success = await _context.SaveChangesAsync() > 0;
            if(success)
                return Json(new {success = true, message = "Operation successful"}, JsonRequestBehavior.AllowGet);
            else
                return Json(new { success = false, message = "Operation failed" }, JsonRequestBehavior.AllowGet);

        }

        public async Task<ActionResult> Edit(string userId)
        {
            //Not implemented on purpose. Focusing on the core features of the applcation
            return View();
        }
    }
}

src/Webapp/Views/Shared/_Alert.cshtml
@{
    if (TempData["success"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["success"].ToString()
        </div>
    }
    if (TempData["message"] != null)
    {
        <div class="alert alert-info" role="alert">
            @TempData["message"].ToString()
        </div>
    }
    if (TempData["failure"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["failure"].ToString()
        </div>
    }
}

src/Webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/lib/jquery-toast-plugin/jquery.toast.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Tasks", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (User.IsInRole("Manager"))
                    {
                        <li>@Html.ActionLink("User management", "Index", "Usermanagement", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content mt-5">
        @Html.Partial("_Alert")
        @RenderBody()
        @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/lib/jquery-toast-plugin/jquery.toast.js"></script>
    <script src="~/Scripts/lib/jqueryui/jquery-ui.js"></script>
    <script>
        function runAlertSuccess(message) {
            if (typeof message === 'undefined') {
                message = 'Operation successful'
            }
            $.toast({
                heading: 'Success',
                text: message,
                showHideTransition: 'slide',
                icon: 'success',
                position: 'top-right'
            })
        }
        function runAlertError(message) {
            if (typeof message === 'undefined') {
                message = 'Operation failed. Contact trial team or try again later'
            }
            $.toast({
                heading: 'Error',
                text: message,
                showHideTransition: 'slide',
                icon: 'error',
                position: 'top-right'
            })
        }
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>