src/Webapp/Controllers/DashboardController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Unity;
using Webapp.Dtos;
using Webapp.Interfaces;
using Webapp.ViewModels;

namespace Webapp.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ITasks _tasks;

        [InjectionConstructor]
        public DashboardController(ITasks tasks)
        {
            _tasks = tasks;
        }
        // GET: Dashboard
        public async Task<ActionResult> Index()
        {
            var userId = User.Identity.GetUserId();
            var tasks = await _tasks.GetAllTasksAsync(userId);
            var result = new DashboardDto();
            if(tasks.Data.Count > 0)
            {
                result.AssociatedTasks = tasks.Data.Count();
                result.CompletedTasks = tasks.Data.Where(x => x.TaskStatusId == 3).Count();
                result.InprogressTasks = tasks.Data.Where(x => x.TaskStatusId == 2).Count();
                result.NotStarted = tasks.Data.Where(x => x.TaskStatusId == 1).Count();
            }
            ViewBag.ManagerYN = User.IsInRole("Manager");
            return View(result);
        }

        public async Task<ActionResult> LoadTasks()
        {
            var userId = User.Identity.GetUserId();
            var tasks = await _tasks.GetTaskIndexAsync(userId);
            
            return Json(new { data = tasks.Data }, JsonRequestBehavior.AllowGet);
        }

      
        public async Task<ActionResult> AutoComplete(string term)
        {
            var result = await _tasks.GetUsers(term);
            return Json(result.Data, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Manager")]
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            var model = new TasksViewModel
            {
                AssigningUserId = userId,
            };
            _tasks.Populatedropdown(model);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TasksViewModel tasks)
        {
            if (!ModelState.IsValid)
            {
                _tasks.Populatedropdown(tasks);
                return View(tasks);
            }
            _tasks.AddTasks(tasks);
            var sucess = await _tasks.SaveChangesAsync();
            if (sucess)
            {
                TempData["success"] = "Task successfully assigned";
                return RedirectToAction(nameof(Index));
            }
            TempData["failure"] = "Problem adding tasks. Please try again"; ;

            _tasks.Populatedropdown(tasks);
            return View(tasks);

        }

        [Authorize(Roles ="Manager")]
        public async Task<ActionResult> Edit(string id)
        {
            var guid = Guid.TryParse(id, out var tasksId);
            if (!guid)
            {
                TempData["failure"] = "Invalid link";
                return RedirectToAction(nameof(Index));
            }
            var model = await _tasks.GetTaskAsync(tasksId);
            if (!model.IsSuccess)
            {
                TempData["failure"] = model.ErrorMessage;
                return RedirectToAction(nameof(Index));
            }
            if (model.Data.AssigningUserId != User.Identity.GetUserId())
            {
                TempData["failure"] = "You do not have access to edit this task";
                return RedirectToAction(nameof(Index));

            }
            _tasks.Populatedropdown(model.Data);
            return View(model.Data);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(TasksViewModel model)
        {
            if (!ModelState.IsValid)
            {
                _tasks.Populatedropdown(model);
                return View(model);
            }
            var result = await _tasks.GetTaskEntityAsync(model.Id);
            result.Data.AssignedToUserId = model.AssignedToUserId ?? result.Data.AssignedToUserId;
            result.Data.Subject = model.Subject ?? result.Data.Subject;
            result.Data.Description = model.Description ?? result.Data.Description;
            result.Data.PriorityId = model.PriorityId;
            result.Data.DateDue = model.DateDue;
            _tasks.UpdateTasks(result.Data);
            var response = await _tasks.SaveChangesAsync();
            if (response)
            {
                TempData["success"] = "Task successfully updated";
                return RedirectToAction(nameof(Index));
            }
            TempData["failure"] = "Operation failed. please try again later";
            _tasks.Populatedropdown(model);
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles ="Manager")]
        public async Task<ActionResult> Delete(string id)
        {
            var guid = Guid.TryParse(id, out var tasksId);
            if (!guid)
            {
                return Json(new {success = false, message = "Invalid link", JsonRequestBehavior.AllowGet });
            }
            var model = await _tasks.GetTaskEntityAsync(tasksId);
            if (!model.IsSuccess)
            {
                return Json(new { success = false, message = model.ErrorMessage, JsonRequestBehavior.AllowGet });

            }
            if (model.Data.AssigningUserId != User.Identity.GetUserId())
            {
                return Json(new { success = false, message = "Only assigned user can delete tasks", JsonRequestBehavior.AllowGet });
            }
            _tasks.RemoveTasks(model.Data);
            var response = await _tasks.SaveChangesAsync();
            if (response)
            {
                return Json(new { success = true, message = "Task successfully deleted", JsonRequestBehavior.AllowGet });

            }
            return Json(new { success = false, message = "Invalid request, please try again later", JsonRequestBehavior.AllowGet });

        }

        [HttpPost]
        public async Task<ActionResult> MarkCompleted(MarkCompleted completed)
        {
            var task = await _tasks.GetTaskEntityAsync(completed.TaskId);
            if (!task.IsSuccess)
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            var model = task.Data;
            model.DateCompleted = completed.CompletedDate;
            model.TaskStatusId = 3;
            _tasks.UpdateTasks(model);
            var success = await _tasks.SaveChangesAsync();
            return Json(new {success = success}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> ChangeToInprogress(string id)
        {
            var guid = Guid.TryParse(id, out var tasksId);
            if (!guid)
            {
                return Json(new { success = false, message="Invalid link" }, JsonRequestBehavior.AllowGet);
            }
            var task = await _tasks.GetTaskEntityAsync(tasksId);
            if (!task.IsSuccess)
            {
                return Json(new { success = false, message = "Invalid link" }, JsonRequestBehavior.AllowGet);
            }
            var result = task.Data;
            result.TaskStatusId = 2;
            _tasks.UpdateTasks(result);
            var success = await _tasks.SaveChangesAsync();
            return Json(new { success = success }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Details(string id)
        {
            var guid = Guid.TryParse(id, out var tasksId);
            if (!guid)
            {
                TempData["failure"] = "Invalid link";
                return RedirectToAction(nameof(Index));
            }
            var model = await _tasks.GetTaskAsync(tasksId);
            if (!model.IsSuccess)
            {
                TempData["failure"] = model.ErrorMessage;
                return RedirectToAction(nameof(Index));
            }
            _tasks.Populatedropdown(model.Data);
            return View(model.Data);
        }
    }
}

src/Webapp/Views/Dashboard/Create.cshtml
@model Webapp.ViewModels.TasksViewModel

@{
    ViewBag.Title = "Data management";
}
<link href="~/Scripts/lib/jqueryui/themes/base/jquery-ui.min.css" rel="stylesheet" />
<nav aria-label="breadcrumb" style="background-color: #d8dce1; padding: .75rem 1rem; border-radius: .25rem">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Dashboard">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Create Tasks</li>
    </ol>
</nav>

<main aria-labelledby="title">
    <div class="card shadow  mt-4">
        <div class="card-header">
            <h3>Add tasks</h3>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Create", "Dashboard", FormMethod.Post, new { role = "form", @class = "p-lg-5 p-sm-1" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.AssignedToUserId)
                @Html.HiddenFor(x => x.AssigningUserId)
                @*@Html.ValidationSummary("", new { @class = "text-danger" })*@
                <div class="row mb-3">
                    @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="row mb-3">
                    @Html.LabelFor(m => m.Description, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(m => m.Description, 10, 10, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                    </div>
                </div>

                @*<div class="row mb-3">
                    @Html.LabelFor(m => m.TaskStatusId, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(m => m.TaskStatusId, Model.Status, "Select status", new { @class = "form-select" })
                        @Html.ValidationMessageFor(model => model.TaskStatusId, "", new { @class = "text-danger" })

                    </div>
                </div>*@
                
                <div class="row mb-3">
                    @Html.LabelFor(m => m.PriorityId, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(m => m.PriorityId, Model.Priority, "Select priority", new { @class = "form-select" })
                        @Html.ValidationMessageFor(model => model.PriorityId, "", new { @class = "text-danger" })

                    </div>
                </div>


                <div class="row mb-3">
                    @Html.LabelFor(m => m.AutoCompletebox, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.AutoCompletebox, new { @class = "form-control" })

                    </div>
                </div>
                <div class="row mb-3">
                    @Html.LabelFor(m => m.DateDue, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.DateDue, new { @class = "form-control", type = "date" })
                        @Html.ValidationMessageFor(model => model.DateDue, "", new { @class = "text-danger" })

                    </div>
                </div>
                <button type="submit" class="btn btn-outline-primary">Assign Task</button>
            }
        </div>
    </div>

</main>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#AutoCompletebox").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Dashboard/AutoComplete",
                        type: "GET",
                        dataType: "JSON",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (val, item) {
                                console.log(val);
                                return {
                                    label: val.FullName,
                                    value: val.FullName,
                                    AutoCompletebox: val.FullName,
                                    Id: val.UserId
                                }
                            }))
                        }
                    })
                },
                change: function (event, ui) {
                    if (ui.item == null) {
                        $("#AutoCompletebox").val("");
                        $("#AutoCompletebox").focus();

                    }
                },
                select: function (event, ui) {
                    //AssignedToUserId
                    $('#AssignedToUserId').val(ui.item.Id);

                }
            });
        });
    </script>
}

src/Webapp/Views/Dashboard/Details.cshtml
@model Webapp.ViewModels.TasksViewModel

@{
    ViewBag.Title = "Edit tasks";
}
<link href="~/Scripts/lib/jqueryui/themes/base/jquery-ui.min.css" rel="stylesheet" />
<nav aria-label="breadcrumb" style="background-color: #d8dce1; padding: .75rem 1rem; border-radius: .25rem">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Dashboard">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Task detail</li>
    </ol>
</nav>

<main aria-labelledby="title">
    <div class="card shadow mt-4">
        <div class="card-header">
            <div>
                <h3>Task detail</h3>
            </div>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("", "", FormMethod.Post, new { role = "form", @class = "p-lg-5 p-sm-1", id="Details" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.AssignedToUserId)
                @Html.HiddenFor(x => x.AssigningUserId)
                @*@Html.ValidationSummary("", new { @class = "text-danger" })*@
                <div class="row mb-3">
                    @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="row mb-3">
                    @Html.LabelFor(m => m.Description, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(m => m.Description, 10, 10, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="row mb-3">
                    @Html.LabelFor(m => m.PriorityId, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(m => m.PriorityId, Model.Priority, "Select priority", new { @class = "form-select" })
                        @Html.ValidationMessageFor(model => model.PriorityId, "", new { @class = "text-danger" })

                    </div>
                </div>


                <div class="row mb-3">
                    @Html.LabelFor(m => m.AutoCompletebox, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.AutoCompletebox, new { @class = "form-control" })

                    </div>
                </div>
                <div class="row mb-3">
                    @Html.LabelFor(m => m.DateDue, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.DateDue, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                        @Html.ValidationMessageFor(model => model.DateDue, "", new { @class = "text-danger" })

                    </div>
                </div>
            }
        </div>
    </div>

</main>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#Details *').prop('disabled', true);
        });


    </script>
}

src/Webapp/Views/Dashboard/Edit.cshtml
@model Webapp.ViewModels.TasksViewModel

@{
    ViewBag.Title = "Edit tasks";
}
<link href="~/Scripts/lib/jqueryui/themes/base/jquery-ui.min.css" rel="stylesheet" />
<nav aria-label="breadcrumb" style="background-color: #d8dce1; padding: .75rem 1rem; border-radius: .25rem">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Dashboard">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit Tasks</li>
    </ol>
</nav>

<main aria-labelledby="title">
    <div class="card shadow  mt-4">
        <div class="card-header">
            <h3>Edit tasks</h3>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Create", "Dashboard", FormMethod.Post, new { role = "form", @class = "p-lg-5 p-sm-1" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.AssignedToUserId)
                @Html.HiddenFor(x => x.AssigningUserId)
                @*@Html.ValidationSummary("", new { @class = "text-danger" })*@
                <div class="row mb-3">
                    @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="row mb-3">
                    @Html.LabelFor(m => m.Description, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(m => m.Description, 10, 10, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="row mb-3">
                    @Html.LabelFor(m => m.PriorityId, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(m => m.PriorityId, Model.Priority, "Select priority", new { @class = "form-select" })
                        @Html.ValidationMessageFor(model => model.PriorityId, "", new { @class = "text-danger" })

                    </div>
                </div>


                <div class="row mb-3">
                    @Html.LabelFor(m => m.AutoCompletebox, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.AutoCompletebox, new { @class = "form-control" })

                    </div>
                </div>
                <div class="row mb-3">
                    @Html.LabelFor(m => m.DateDue, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.TextBoxFor(m => m.DateDue, "{0:yyyy-MM-dd}", new { @class = "form-control", type="date" })
                        @Html.ValidationMessageFor(model => model.DateDue, "", new { @class = "text-danger" })

                    </div>
                </div>
                <button type="submit" class="btn btn-outline-primary">Edit Task</button>
            }
        </div>
    </div>

</main>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#AutoCompletebox").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Dashboard/AutoComplete",
                        type: "GET",
                        dataType: "JSON",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (val, item) {
                                console.log(val);
                                return {
                                    label: val.FullName,
                                    value: val.FullName,
                                    AutoCompletebox: val.FullName,
                                    Id: val.UserId
                                }
                            }))
                        }
                    })
                },
                change: function (event, ui) {
                    if (ui.item == null) {
                        $("#AutoCompletebox").val("");
                        $("#AutoCompletebox").focus();

                    }
                },
                select: function (event, ui) {
                    //AssignedToUserId
                    $('#AssignedToUserId').val(ui.item.Id);

                }
            });
        });


    </script>
}